version: "3.8"
services:
  db:
    image: postgres
    env_file:
      - ./.dev.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "mailing"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: mailing_app
    env_file:
      - ./.dev.env
    command: ./run.sh
    ports:
      - 8000:8000
    volumes:
      - ./mailing/:/app
    depends_on:
      - db

  celery:
    image: mailing_app
    command: celery -A mailing.celery worker --loglevel=INFO
    env_file:
      - ./.dev.env
    volumes:
      - ./mailing/:/app
    depends_on:
      - app
      - rabbitmq

  rabbitmq:
    image: rabbitmq

  redis:
    image: redis
