version: "3.8"
services:
  # db:
  #   image: postgres
  #   env_file:
  #     - ./.dev.env
  app:
    image: mailing_app
    # build: ./mailing
    env_file:
      - ./.dev.env
    command: ./run.sh
    ports:
      - 8000:8000
    volumes:
      - ./mailing/:/app
