# Generated by Django 4.1.4 on 2022-12-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_operator',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
